/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/legal-sources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Legal Sources */
        get: operations["list_legal_sources_api_v1_legal_sources_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/legal-sources/{source_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Legal Source */
        get: operations["get_legal_source_api_v1_legal_sources__source_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/analyses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Analysis */
        post: operations["create_analysis_api_v1_analyses_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/conversations/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Conversation Turn */
        post: operations["create_conversation_turn_api_v1_conversations_messages_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/cases": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Cases */
        get: operations["list_cases_api_v1_cases_get"];
        put?: never;
        /** Create Case */
        post: operations["create_case_api_v1_cases_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/cases/{case_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Case */
        get: operations["get_case_api_v1_cases__case_id__get"];
        put?: never;
        post?: never;
        /** Delete Case */
        delete: operations["delete_case_api_v1_cases__case_id__delete"];
        options?: never;
        head?: never;
        /** Update Case */
        patch: operations["update_case_api_v1_cases__case_id__patch"];
        trace?: never;
    };
    "/api/v1/cases/{case_id}/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Update Case Profile */
        put: operations["update_case_profile_api_v1_cases__case_id__profile_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/cases/{case_id}/materials": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Case Materials */
        get: operations["list_case_materials_api_v1_cases__case_id__materials_get"];
        put?: never;
        /** Add Case Material */
        post: operations["add_case_material_api_v1_cases__case_id__materials_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/cases/{case_id}/materials/upload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload Case Material */
        post: operations["upload_case_material_api_v1_cases__case_id__materials_upload_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/cases/{case_id}/materials/{material_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Case Material */
        delete: operations["delete_case_material_api_v1_cases__case_id__materials__material_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/cases/{case_id}/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Case Conversation Messages */
        get: operations["list_case_conversation_messages_api_v1_cases__case_id__messages_get"];
        put?: never;
        /** Create Case Conversation Turn */
        post: operations["create_case_conversation_turn_api_v1_cases__case_id__messages_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/cases/{case_id}/messages/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Stream Case Conversation Turn */
        post: operations["stream_case_conversation_turn_api_v1_cases__case_id__messages_stream_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/cases/{case_id}/run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Case Run */
        get: operations["get_case_run_api_v1_cases__case_id__run_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/cases/{case_id}/run/activities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Case Run Activities */
        get: operations["get_case_run_activities_api_v1_cases__case_id__run_activities_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/cases/{case_id}/runs/{run_id}/events/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Stream Existing Case Run */
        get: operations["stream_existing_case_run_api_v1_cases__case_id__runs__run_id__events_stream_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/cases/{case_id}/run/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancel Case Run */
        post: operations["cancel_case_run_api_v1_cases__case_id__run_cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Body_upload_case_material_api_v1_cases__case_id__materials_upload_post */
        Body_upload_case_material_api_v1_cases__case_id__materials_upload_post: {
            /** File */
            file: string;
            /** @default other */
            kind: components["schemas"]["MaterialKind"];
            /** Source Note */
            source_note?: string | null;
        };
        /** CaseAnalysisRequest */
        CaseAnalysisRequest: {
            /** Case Title */
            case_title: string;
            /** Case Background */
            case_background?: string | null;
            /** Questions */
            questions?: string[];
            /** Materials */
            materials: components["schemas"]["CaseMaterial"][];
        };
        /** CaseAnalysisResult */
        CaseAnalysisResult: {
            /**
             * Analysis Id
             * Format: uuid
             */
            analysis_id: string;
            /** Case Title */
            case_title: string;
            /** Analysis */
            analysis: string;
            /** Material Count */
            material_count: number;
            /** Runtime Thread Id */
            runtime_thread_id?: string | null;
            /**
             * Disclaimer
             * @default 本分析由 AI 基于所提交材料生成，仅用于案件研究和材料整理，不构成法律意见，不能替代执业律师对事实、证据及适用法律的审查。
             */
            disclaimer: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at?: string;
        };
        /** CaseConversationMessage */
        CaseConversationMessage: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Thread Id
             * Format: uuid
             */
            thread_id: string;
            /**
             * Run Id
             * Format: uuid
             */
            run_id: string;
            /** Role */
            role: string;
            /** Content */
            content: string;
            /** Legal Citations */
            legal_citations?: components["schemas"]["LegalCitation"][];
            /** Case Law Citations */
            case_law_citations?: components["schemas"]["CaseLawCitation"][];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** CaseConversationTurnRequest */
        CaseConversationTurnRequest: {
            /** Message */
            message: string;
        };
        /** CaseConversationTurnResult */
        CaseConversationTurnResult: {
            /**
             * Case Id
             * Format: uuid
             */
            case_id: string;
            /**
             * Thread Id
             * Format: uuid
             */
            thread_id: string;
            /**
             * Run Id
             * Format: uuid
             */
            run_id: string;
            /** Case Title */
            case_title: string;
            /** Assistant Message */
            assistant_message: string;
            /** Material Count */
            material_count: number;
            /** Legal Citations */
            legal_citations?: components["schemas"]["LegalCitation"][];
            /** Case Law Citations */
            case_law_citations?: components["schemas"]["CaseLawCitation"][];
            /**
             * Profile Updated
             * @default false
             */
            profile_updated: boolean;
            case_profile?: components["schemas"]["CaseProfile"];
        };
        /** CaseFactor */
        CaseFactor: {
            /** Key */
            key: string;
            /** Label */
            label: string;
            type: components["schemas"]["FactorType"];
            /** @default unknown */
            state: components["schemas"]["FactorState"];
            /** Value */
            value?: boolean | number | string | null;
            /** @default medium */
            materiality: components["schemas"]["FactorMateriality"];
            /** Question */
            question?: string | null;
            /** Source Turns */
            source_turns?: number[];
            /** Source Material Refs */
            source_material_refs?: string[];
        };
        /** CaseFactorProfile */
        CaseFactorProfile: {
            /** Active Domains */
            active_domains?: string[];
            /** Factors */
            factors?: components["schemas"]["CaseFactor"][];
        };
        /** CaseLawCitation */
        CaseLawCitation: {
            /** Reference */
            reference: string;
            /** Case Number */
            case_number: string;
            /** Title */
            title: string;
            /** Section Label */
            section_label: string;
            /** Issuing Authority */
            issuing_authority: string;
            /** Source Url */
            source_url: string;
            /** Published On */
            published_on: string | null;
            /** Content */
            content?: string | null;
        };
        /** CaseMaterial */
        CaseMaterial: {
            /**
             * Material Id
             * Format: uuid
             */
            material_id?: string;
            /** Title */
            title: string;
            /** @default other */
            kind: components["schemas"]["MaterialKind"];
            /** Content */
            content: string;
            /** Source Note */
            source_note?: string | null;
        };
        /** CaseProfile */
        CaseProfile: {
            /** Case Type */
            case_type?: string | null;
            /** Parties */
            parties?: string[];
            /** Claims */
            claims?: string[];
            /** Key Facts */
            key_facts?: string[];
            /** Disputed Issues */
            disputed_issues?: string[];
            /** Evidence Notes */
            evidence_notes?: string[];
            /** Missing Information */
            missing_information?: string[];
            factor_profile?: components["schemas"]["CaseFactorProfile"];
            /**
             * Pending Answer Targets
             * @description Application-maintained targets that a factual follow-up can continue answering.
             */
            pending_answer_targets?: components["schemas"]["LegalTurnAnswerTarget"][];
        };
        /** CaseProfileUpdate */
        CaseProfileUpdate: {
            /** Case Type */
            case_type?: string | null;
            /** Parties */
            parties?: string[];
            /** Claims */
            claims?: string[];
            /** Key Facts */
            key_facts?: string[];
            /** Disputed Issues */
            disputed_issues?: string[];
            /** Evidence Notes */
            evidence_notes?: string[];
            /** Missing Information */
            missing_information?: string[];
            factor_profile?: components["schemas"]["CaseFactorProfile"];
            /**
             * Pending Answer Targets
             * @description Application-maintained targets that a factual follow-up can continue answering.
             */
            pending_answer_targets?: components["schemas"]["LegalTurnAnswerTarget"][];
        };
        /** CaseRun */
        CaseRun: {
            /**
             * Run Id
             * Format: uuid
             */
            run_id: string;
            status: components["schemas"]["CaseRunStatus"];
            /** Model Name */
            model_name?: string | null;
            /** Error */
            error?: string | null;
            /**
             * Message Count
             * @default 0
             */
            message_count: number;
            /** First Human Message */
            first_human_message?: string | null;
            /** Last Ai Message */
            last_ai_message?: string | null;
            /** Started At */
            started_at?: string | null;
            /** Completed At */
            completed_at?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** CaseRunActivity */
        CaseRunActivity: {
            /** Seq */
            seq: number;
            type: components["schemas"]["CaseRunActivityType"];
            /** Event Type */
            event_type: string;
            call_index?: number | null;
            /** Content */
            content?: string | null;
            /** Call Id */
            call_id?: string | null;
            /** Caller */
            caller?: string | null;
            /** Description */
            description?: string | null;
            /** Display Name */
            display_name?: string | null;
            /** Kind */
            kind?: string | null;
            /** Latency Ms */
            latency_ms?: number | null;
            /** Parent Call Id */
            parent_call_id?: string | null;
            /** Status */
            status?: string | null;
            /** Tool Name */
            tool_name?: string | null;
            /** Subagent Type */
            subagent_type?: string | null;
            /** Task Id */
            task_id?: string | null;
        };
        /** CaseRunActivityHistory */
        CaseRunActivityHistory: {
            /**
             * Run Id
             * Format: uuid
             */
            run_id: string;
            status: components["schemas"]["CaseRunStatus"];
            /** Activities */
            activities?: components["schemas"]["CaseRunActivity"][];
            /** Completed At */
            completed_at?: string | null;
        };
        /**
         * CaseRunActivityType
         * @enum {string}
         */
        CaseRunActivityType: "model_started" | "model_completed" | "model_failed" | "tool_started" | "tool_completed" | "tool_failed" | "task_started" | "task_running" | "task_completed" | "task_failed" | "task_timed_out";
        /**
         * CaseRunStatus
         * @enum {string}
         */
        CaseRunStatus: "queued" | "running" | "needs_clarification" | "completed" | "failed" | "cancelled";
        /** ConversationTurnRequest */
        ConversationTurnRequest: {
            /** Thread Id */
            thread_id?: string | null;
            /** Message */
            message: string;
            /** Case Title */
            case_title?: string | null;
            case_profile?: components["schemas"]["CaseProfile"] | null;
            /** Materials */
            materials?: components["schemas"]["CaseMaterial"][];
        };
        /** ConversationTurnResult */
        ConversationTurnResult: {
            /**
             * Thread Id
             * Format: uuid
             */
            thread_id: string;
            /** Assistant Message */
            assistant_message: string;
            /** Material Count */
            material_count: number;
            /**
             * Disclaimer
             * @default 本分析由 AI 基于所提交材料生成，仅用于案件研究和材料整理，不构成法律意见，不能替代执业律师对事实、证据及适用法律的审查。
             */
            disclaimer: string;
        };
        /**
         * FactorMateriality
         * @enum {string}
         */
        FactorMateriality: "high" | "medium" | "low";
        /**
         * FactorState
         * @enum {string}
         */
        FactorState: "asserted" | "denied" | "unknown" | "conflicting";
        /**
         * FactorType
         * @enum {string}
         */
        FactorType: "text" | "numeric" | "boolean" | "categorical";
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /** Status */
            status: string;
            /** Service */
            service: string;
            /** Version */
            version: string;
        };
        /** LegalCase */
        LegalCase: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Title */
            title: string;
            /** Background */
            background: string | null;
            profile?: components["schemas"]["CaseProfile"];
            /** Material Count */
            material_count: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** LegalCaseCreate */
        LegalCaseCreate: {
            /** Title */
            title: string;
            /** Background */
            background?: string | null;
        };
        /** LegalCaseUpdate */
        LegalCaseUpdate: {
            /** Title */
            title: string;
        };
        /** LegalCitation */
        LegalCitation: {
            /** Reference */
            reference: string;
            /** Title */
            title: string;
            /** Article Label */
            article_label: string | null;
            /** Issuing Authority */
            issuing_authority: string;
            /** Source Url */
            source_url: string;
            status: components["schemas"]["LegalSourceStatus"];
            /** Content */
            content?: string | null;
        };
        /** LegalSourceDetail */
        LegalSourceDetail: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Title */
            title: string;
            kind: components["schemas"]["LegalSourceKind"];
            /** Issuing Authority */
            issuing_authority: string;
            status: components["schemas"]["LegalSourceStatus"];
            /** Published On */
            published_on: string | null;
            /** Effective On */
            effective_on: string | null;
            /** Source Name */
            source_name: string;
            /** Source Url */
            source_url: string;
            /** Version Label */
            version_label: string | null;
            review_status: components["schemas"]["LegalSourceReviewStatus"];
            /** Content Sha256 */
            content_sha256: string;
            /** Verified At */
            verified_at: string | null;
            /** Chunk Count */
            chunk_count: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Content */
            content: string;
        };
        /**
         * LegalSourceKind
         * @enum {string}
         */
        LegalSourceKind: "law" | "administrative_regulation" | "judicial_interpretation" | "department_rule" | "local_regulation" | "other";
        /**
         * LegalSourceReviewStatus
         * @enum {string}
         */
        LegalSourceReviewStatus: "pending" | "approved" | "rejected";
        /**
         * LegalSourceStatus
         * @enum {string}
         */
        LegalSourceStatus: "effective" | "amended" | "repealed" | "not_effective";
        /** LegalSourceSummary */
        LegalSourceSummary: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Title */
            title: string;
            kind: components["schemas"]["LegalSourceKind"];
            /** Issuing Authority */
            issuing_authority: string;
            status: components["schemas"]["LegalSourceStatus"];
            /** Published On */
            published_on: string | null;
            /** Effective On */
            effective_on: string | null;
            /** Source Name */
            source_name: string;
            /** Source Url */
            source_url: string;
            /** Version Label */
            version_label: string | null;
            review_status: components["schemas"]["LegalSourceReviewStatus"];
            /** Content Sha256 */
            content_sha256: string;
            /** Verified At */
            verified_at: string | null;
            /** Chunk Count */
            chunk_count: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * LegalTurnAnswerKind
         * @enum {string}
         */
        LegalTurnAnswerKind: "rule" | "classification" | "estimate" | "calculation" | "action";
        /**
         * LegalTurnAnswerMode
         * @enum {string}
         */
        LegalTurnAnswerMode: "direct" | "conditional";
        /** LegalTurnAnswerTarget */
        LegalTurnAnswerTarget: {
            /**
             * Question
             * @description One question the user actually asked, without adding a new issue.
             */
            question: string;
            /** @description Use direct when current facts support a bounded answer; use conditional when the answer must show explicit branches. Neither mode permits withholding the answer. */
            mode: components["schemas"]["LegalTurnAnswerMode"];
            /** @description Classify the requested deliverable. Rule and classification targets are answered with bounded branches and do not trigger automatic follow-up questions. */
            kind: components["schemas"]["LegalTurnAnswerKind"];
        };
        /**
         * MaterialKind
         * @enum {string}
         */
        MaterialKind: "complaint" | "defense" | "contract" | "evidence" | "transcript" | "judgment" | "statute" | "other";
        /** StoredCaseMaterial */
        StoredCaseMaterial: {
            /**
             * Material Id
             * Format: uuid
             */
            material_id?: string;
            /** Title */
            title: string;
            /** @default other */
            kind: components["schemas"]["MaterialKind"];
            /** Content */
            content: string;
            /** Source Note */
            source_note?: string | null;
            /**
             * Case Id
             * Format: uuid
             */
            case_id: string;
            /** Reference Index */
            reference_index: number;
            /** Original Filename */
            original_filename?: string | null;
            /** Media Type */
            media_type?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    list_legal_sources_api_v1_legal_sources_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LegalSourceSummary"][];
                };
            };
        };
    };
    get_legal_source_api_v1_legal_sources__source_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                source_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LegalSourceDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_analysis_api_v1_analyses_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CaseAnalysisRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CaseAnalysisResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_conversation_turn_api_v1_conversations_messages_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConversationTurnRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConversationTurnResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_cases_api_v1_cases_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LegalCase"][];
                };
            };
        };
    };
    create_case_api_v1_cases_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LegalCaseCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LegalCase"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_case_api_v1_cases__case_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                case_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LegalCase"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_case_api_v1_cases__case_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                case_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_case_api_v1_cases__case_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                case_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LegalCaseUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LegalCase"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_case_profile_api_v1_cases__case_id__profile_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                case_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CaseProfileUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LegalCase"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_case_materials_api_v1_cases__case_id__materials_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                case_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StoredCaseMaterial"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_case_material_api_v1_cases__case_id__materials_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                case_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CaseMaterial"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StoredCaseMaterial"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_case_material_api_v1_cases__case_id__materials_upload_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                case_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_case_material_api_v1_cases__case_id__materials_upload_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StoredCaseMaterial"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_case_material_api_v1_cases__case_id__materials__material_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                case_id: string;
                material_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_case_conversation_messages_api_v1_cases__case_id__messages_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                case_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CaseConversationMessage"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_case_conversation_turn_api_v1_cases__case_id__messages_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                case_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CaseConversationTurnRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CaseConversationTurnResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stream_case_conversation_turn_api_v1_cases__case_id__messages_stream_post: {
        parameters: {
            query?: never;
            header?: {
                "Last-Event-ID"?: string | null;
            };
            path: {
                case_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CaseConversationTurnRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_case_run_api_v1_cases__case_id__run_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                case_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CaseRun"] | null;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_case_run_activities_api_v1_cases__case_id__run_activities_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                case_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CaseRunActivityHistory"] | null;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stream_existing_case_run_api_v1_cases__case_id__runs__run_id__events_stream_get: {
        parameters: {
            query?: never;
            header?: {
                "Last-Event-ID"?: string | null;
            };
            path: {
                case_id: string;
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_case_run_api_v1_cases__case_id__run_cancel_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                case_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CaseRun"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
