"""Legal case domain models."""

from lexora_ai.domain.case_law import (
    CaseLawChunk,
    CaseLawCitation,
    CaseLawSourceCreate,
    CaseLawSourceDetail,
    CaseLawSourceSummary,
    CaseLawSourceUpdate,
    CaseLawStatus,
)
from lexora_ai.domain.cases import (
    CaseAnalysisRequest,
    CaseAnalysisResult,
    CaseMaterial,
    MaterialKind,
)
from lexora_ai.domain.conversations import ConversationTurnRequest, ConversationTurnResult
from lexora_ai.domain.legal_knowledge import (
    LegalCitation,
    LegalKnowledgeChunk,
    LegalSourceCreate,
    LegalSourceDetail,
    LegalSourceKind,
    LegalSourceReviewStatus,
    LegalSourceStatus,
    LegalSourceSummary,
    LegalSourceUpdate,
)
from lexora_ai.domain.runs import CaseRun, CaseRunStatus
from lexora_ai.domain.workspaces import (
    CaseConversationMessage,
    CaseConversationTurnRequest,
    CaseConversationTurnResult,
    CaseProfile,
    CaseProfilePatch,
    CaseProfileUpdate,
    LegalCase,
    LegalCaseCreate,
    LegalCaseUpdate,
    MaterialUploadMetadata,
    StoredCaseMaterial,
    StoredMaterialChunk,
)

__all__ = [
    "CaseAnalysisRequest",
    "CaseAnalysisResult",
    "CaseLawChunk",
    "CaseLawCitation",
    "CaseLawSourceCreate",
    "CaseLawSourceDetail",
    "CaseLawSourceSummary",
    "CaseLawSourceUpdate",
    "CaseLawStatus",
    "CaseRun",
    "CaseRunStatus",
    "CaseMaterial",
    "CaseProfile",
    "CaseProfilePatch",
    "CaseProfileUpdate",
    "CaseConversationMessage",
    "CaseConversationTurnRequest",
    "CaseConversationTurnResult",
    "ConversationTurnRequest",
    "ConversationTurnResult",
    "LegalCase",
    "LegalCaseCreate",
    "LegalCaseUpdate",
    "LegalCitation",
    "LegalKnowledgeChunk",
    "LegalSourceCreate",
    "LegalSourceDetail",
    "LegalSourceKind",
    "LegalSourceReviewStatus",
    "LegalSourceStatus",
    "LegalSourceSummary",
    "LegalSourceUpdate",
    "MaterialKind",
    "MaterialUploadMetadata",
    "StoredCaseMaterial",
    "StoredMaterialChunk",
]
