"""Legal case domain models."""

from lexora_ai.domain.case_law import (
    CaseLawChunk,
    CaseLawCitation,
    CaseLawSourceCreate,
    CaseLawSourceDetail,
    CaseLawSourceSummary,
    CaseLawSourceUpdate,
    CaseLawStatus,
)
from lexora_ai.domain.cases import (
    CaseAnalysisRequest,
    CaseAnalysisResult,
    CaseMaterial,
    MaterialKind,
)
from lexora_ai.domain.conversations import ConversationTurnRequest, ConversationTurnResult
from lexora_ai.domain.factor_discovery import (
    FactorDiscoveryBatch,
    FactorDiscoveryBudget,
    FactorDiscoveryCandidate,
    FactorDiscoveryLoadResult,
    FactorDiscoveryPlan,
    FactorTokenBudgetSnapshot,
    FactorTokenReservation,
)
from lexora_ai.domain.factors import (
    CaseFactor,
    CaseFactorProfile,
    FactorDefinition,
    FactorMateriality,
    FactorState,
    FactorType,
)
from lexora_ai.domain.legal_knowledge import (
    LegalCitation,
    LegalKnowledgeChunk,
    LegalSourceCreate,
    LegalSourceDetail,
    LegalSourceKind,
    LegalSourceReviewStatus,
    LegalSourceStatus,
    LegalSourceSummary,
    LegalSourceUpdate,
)
from lexora_ai.domain.legal_turns import (
    LegalTurnFactorUpdate,
    LegalTurnIntent,
    LegalTurnPreparation,
)
from lexora_ai.domain.research_benchmarks import (
    ResearchBenchmarkPlan,
    ResearchRelevanceJudgment,
    ResearchRelevanceLoadResult,
)
from lexora_ai.domain.research_datasets import (
    NormalizedResearchRecord,
    ResearchDatasetLoadResult,
    ResearchDuplicateGroup,
    ResearchNormalizationPlan,
    ResearchRecordKind,
)
from lexora_ai.domain.runs import CaseRun, CaseRunStatus
from lexora_ai.domain.sufficiency import FollowUpQuestion, SufficiencyDecision, SufficiencyGate
from lexora_ai.domain.workspaces import (
    CaseConversationMessage,
    CaseConversationTurnRequest,
    CaseConversationTurnResult,
    CaseProfile,
    CaseProfilePatch,
    CaseProfileUpdate,
    LegalCase,
    LegalCaseCreate,
    LegalCaseUpdate,
    MaterialUploadMetadata,
    StoredCaseMaterial,
    StoredMaterialChunk,
)

__all__ = [
    "CaseAnalysisRequest",
    "CaseAnalysisResult",
    "CaseFactor",
    "CaseFactorProfile",
    "CaseLawChunk",
    "CaseLawCitation",
    "CaseLawSourceCreate",
    "CaseLawSourceDetail",
    "CaseLawSourceSummary",
    "CaseLawSourceUpdate",
    "CaseLawStatus",
    "CaseRun",
    "CaseRunStatus",
    "CaseMaterial",
    "CaseProfile",
    "CaseProfilePatch",
    "CaseProfileUpdate",
    "CaseConversationMessage",
    "CaseConversationTurnRequest",
    "CaseConversationTurnResult",
    "ConversationTurnRequest",
    "ConversationTurnResult",
    "FollowUpQuestion",
    "FactorDefinition",
    "FactorDiscoveryBatch",
    "FactorDiscoveryBudget",
    "FactorDiscoveryCandidate",
    "FactorDiscoveryLoadResult",
    "FactorDiscoveryPlan",
    "FactorTokenBudgetSnapshot",
    "FactorTokenReservation",
    "FactorMateriality",
    "FactorState",
    "FactorType",
    "LegalCase",
    "LegalCaseCreate",
    "LegalCaseUpdate",
    "LegalCitation",
    "LegalKnowledgeChunk",
    "LegalSourceCreate",
    "LegalSourceDetail",
    "LegalSourceKind",
    "LegalSourceReviewStatus",
    "LegalSourceStatus",
    "LegalSourceSummary",
    "LegalSourceUpdate",
    "LegalTurnFactorUpdate",
    "LegalTurnIntent",
    "LegalTurnPreparation",
    "MaterialKind",
    "MaterialUploadMetadata",
    "NormalizedResearchRecord",
    "ResearchBenchmarkPlan",
    "ResearchDatasetLoadResult",
    "ResearchDuplicateGroup",
    "ResearchNormalizationPlan",
    "ResearchRecordKind",
    "ResearchRelevanceJudgment",
    "ResearchRelevanceLoadResult",
    "StoredCaseMaterial",
    "StoredMaterialChunk",
    "SufficiencyDecision",
    "SufficiencyGate",
]
